name: Publish the Docker image in DockerHub

on:
  release:
    types: [released]

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Prepare Tags
        id: prepare-tags
        run: |
          echo ::set-output name=git-tag::${GITHUB_REF#refs/tags/}
          echo ::set-output name=git-short-sha::${GITHUB_SHA::7}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_REPO }}:latest
            ${{ secrets.DOCKER_REPO }}:${{ steps.prepare-tags.outputs.git-tag }}
            ${{ secrets.DOCKER_REPO }}:${{ steps.prepare-tags.outputs.git-short-sha }}
